### PR TITLE
use :q to quote prompt to accomodate prompts with embedded newlines

### PR DESCRIPTION
**Pull request by snmishra**
The default prompt on CentOS has an embedded newline. Saving the old prompt variable using "$prompt" doesn't work, but $prompt:q does.

### CODE REVIEW

**Comment by xdelaruelle** [comment]
@snmishra Could you provide for the record a `$prompt` value that demonstrate the issue with the current quote escaping?

**Comment by xdelaruelle** [comment]
Ok I have found one:

```
set prompt='[%n@%m %c]%# \\
>'
```

**Comment by snmishra** [comment]
@xdelaruelle Actually not the default on CentOS, my bad. It was some customization I had for tcsh only. The prompt is from https://sourceforge.net/p/tcshrc/code/HEAD/tree/trunk/tcshrc/src/tcshrc.set
tcsh is not my normal shell, but it's widely used in the integrated circuit tools world. So I test it occasionally.
The specific prompt I was using is:
```
set prompt='\
%B%n%b@%U%m%u %S%/%s\
%# '
```

**Comment by xdelaruelle** [comment]
Thanks for this contribution.

**Pull request merged**
