### PR TITLE
Fix ShellCheck reports - Part 1

### PR DESCRIPTION
**Pull request by lzaoral**
This PR is the first one in the series to address all ShellCheck reports in this project.  See the commit messages for additional information.

* init: add vim modeline to {,b,k}sh scripts
* lint(ShellCheck): fix SC2148 error
* lint(ShellCheck): fix SC2068 error
* lint(ShellCheck): fix SC1035 error
* lint(ShellCheck): fix SC2166 warning
* lint(ShellCheck): fix SC2178 warning
* lint(ShellCheck): fix SC2048 warning
* lint(ShellCheck): fix SC2128 warning
* lint(ShellCheck): fix SC2155 warning
* lint(ShellCheck): fix SC2086 info diagnostic
* lint(ShellCheck): fix SC2046 warning

Related: #470

### CODE REVIEW

**Comment by lzaoral** [comment]
Please ignore the Differential ShellCheck failure.  Due to 0796a1a, ShellCheck now recognizes additional files as shell scripts and will report all detected problems in such files as new.

**Comment by lzaoral** [comment]
I've dropped df8d81a since it completely broke `testsuite/bin/install_test_sh`. And a few quoted shell variables that shouldn't be quoted after all.  Hopefully, the

**Comment by xdelaruelle** [comment]
This is great, thanks a lot for this contribution.

Maybe some shellcheck ignore directive could be added in c9e78c8, to mention that `_mlre` variable need some expansion. But maybe you have other plans with PR part2.

Somehow 50/140 test from modules testsuite fails on some CI environment.

**Comment by xdelaruelle** [comment]
I have fixed SC2048 commit to correct `testsuite/cmd.exe` script that needs word expansion from string to work as expected to perform tests.

I have added shellcheck directive in `init/*.in` files for SC2086, as word splitting is expected on `_mlre` variable.

I have merged these modifications in the initial "fix SCXXXX" commit.

On my side, I have added to `lint` testsuite to test for the moment sh, bash, bash and tcl scripts against a linter. I have rebased the branch over these new additions on the master branch.

**Comment by lzaoral** [comment]
Wow, thank you @xdelaruelle!  Unfortunately, I was offline yesterday so hadn't the chance to reply sooner.

**Pull request merged**
